### ISSUE TITLE
ClientDB фиксация контактных данных тех кто открывает ТТ в формате cc_*

### ISSUE THREAD

**Issue by GoogleCodeExporter** [VsMoroz/tt-system-data#12]
```
Необходимо модернизировать Client DB так что 
бы в БДСЭ фиксировались телефоны,email и 
контактные данные  в формате сс_*

Детально формат данных описан во вложенном 
файле
```

Original issue reported on code.google.com by `rf40...@gmail.com` on 29 Jul 2014 at 11:40

Attachments:
* [2014_07_10_контактные данные в формате cc_.doc](https://storage.googleapis.com/google-code-attachments/tt-system-data/issue-12/comment-0/2014_07_10_контактные данные в формате cc_.doc)

**Comment by VsMoroz** [comment]
это выполненно
